import React from "react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#FAFAFA] font-sans px-6 py-12 max-w-3xl mx-auto">
      <div className="mb-8">
        <a href="/" className="text-xs text-zinc-400 hover:text-zinc-700 transition-colors">← Back to Violet</a>
      </div>
      <div className="flex items-center gap-2 mb-2">
        <span className="text-2xl">🌸</span>
        <h1 className="text-2xl font-extrabold tracking-tight text-zinc-900">Terms of Service</h1>
      </div>
      <p className="text-xs text-zinc-400 mb-8">Last updated: June 17, 2026</p>

      <div className="space-y-6 text-sm text-zinc-700 leading-relaxed">
        <section>
          <h2 className="font-bold text-zinc-900 mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using Violet Career OS ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">2. Description of Service</h2>
          <p>Violet is an AI-powered career co-pilot that helps you analyze job opportunities, tailor application materials, track applications, and prepare for interviews. All AI-generated actions require your explicit approval before execution.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">3. User Accounts</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information when creating an account.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">4. Acceptable Use</h2>
          <p>You agree not to misuse the Service, including but not limited to: attempting to gain unauthorized access, transmitting malicious code, scraping or harvesting data, or using the Service for any unlawful purpose.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">5. AI-Generated Content</h2>
          <p>Content generated by Violet's AI features is provided for informational and productivity purposes only. You are solely responsible for reviewing, editing, and approving any AI-generated content before use. Violet makes no guarantees about the accuracy or fitness of AI outputs.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">6. Intellectual Property</h2>
          <p>You retain ownership of all content you submit. By using the Service, you grant Violet a limited license to process your content solely to provide the Service.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">7. Limitation of Liability</h2>
          <p>Violet is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">8. Changes to Terms</h2>
          <p>We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
        </section>

        <section>
          <h2 className="font-bold text-zinc-900 mb-2">9. Contact</h2>
          <p>For questions about these terms, contact us at <a href="mailto:support@violet.app" className="text-zinc-900 underline">support@violet.app</a>.</p>
        </section>
      </div>
    </div>
  );
}
